"""Add command lifecycle fields

Revision ID: a224ad0c4028
Revises: 
Create Date: 2026-07-19 13:41:47.933564
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a224ad0c4028'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robot_commands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('command_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('robot_id', 'idempotency_key', name='uix_robot_id_idempotency_key')
    )
    op.create_index(op.f('ix_robot_commands_id'), 'robot_commands', ['id'], unique=False)
    op.create_index(op.f('ix_robot_commands_robot_id'), 'robot_commands', ['robot_id'], unique=False)
    op.create_index('ix_robot_commands_robot_id_desc', 'robot_commands', ['robot_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('battery', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('mission_id', sa.String(length=64), nullable=True),
    sa.Column('mission_type', sa.String(length=32), nullable=True),
    sa.Column('mission_progress', sa.Float(), nullable=True),
    sa.Column('mission_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('battery_health', sa.Float(), nullable=True),
    sa.Column('motor_health', sa.Float(), nullable=True),
    sa.Column('sensor_health', sa.Float(), nullable=True),
    sa.Column('network_health', sa.Float(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_robot_id'), 'telemetry', ['robot_id'], unique=False)
    op.create_index('ix_telemetry_robot_id_desc', 'telemetry', ['robot_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('ix_telemetry_robot_timestamp', 'telemetry', ['robot_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_status'), 'telemetry', ['status'], unique=False)
    op.create_index(op.f('ix_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_timestamp'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_status'), table_name='telemetry')
    op.drop_index('ix_telemetry_robot_timestamp', table_name='telemetry')
    op.drop_index('ix_telemetry_robot_id_desc', table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_robot_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index('ix_robot_commands_robot_id_desc', table_name='robot_commands')
    op.drop_index(op.f('ix_robot_commands_robot_id'), table_name='robot_commands')
    op.drop_index(op.f('ix_robot_commands_id'), table_name='robot_commands')
    op.drop_table('robot_commands')
    # ### end Alembic commands ###
