"""Sync models

Revision ID: cecf3447d0de
Revises: a224ad0c4028
Create Date: 2026-07-21 19:09:41.638092
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cecf3447d0de'
down_revision: Union[str, None] = 'a224ad0c4028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('firmware_version', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('decommissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robots_id'), 'robots', ['id'], unique=False)
    op.create_index('ix_robot_commands_robot_id_status', 'robot_commands', ['robot_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_robot_commands_robot_id_status', table_name='robot_commands')
    op.drop_index(op.f('ix_robots_id'), table_name='robots')
    op.drop_table('robots')
    # ### end Alembic commands ###
